### ISSUE TITLE
Web library build no longer works

### ISSUE THREAD

**Issue by tnajdek** [zotero/pdf-reader#100]
The latest version no longer works with Web Library, reporting `Invalid or corrupted PDF file` for every file. I suspect this is due to a 8aca35a0, particuilarly [this change](https://github.com/zotero/pdf-reader/blob/8aca35a03f563743366c5e5230e24f2f34c4aaa9/src/viewer.js#L135). It has previously been decided that Web Library should be [sending an URL](https://github.com/zotero/pdf-reader/blob/3b7f54727fdd8f238281a555988ada4615679b9c/src/index.web.js#L110) but from what I understand it is no longer accepted.

Should I tweak web library so it sends data via message? If we do, we probably don't want to call it `url` to avoid confusion.

**Comment by mrtcode** [comment]
After upgrading PDF.js, there are changes to how it accepts various data sources. I've addressed the regressions for now, however, in future pdf-reader versions, you will likely need to pass the buffer regardless, although postMessage will no longer be necessary.
