### ISSUE TITLE
Links inside pdf's not working

### ISSUE THREAD

**Issue by masteranza** [zotero/pdf-reader#59]
Frankly, I'm quite surprised to be the first one to add this issue, but not being able to follow hyperlinks in pdf's seems like the first thing one notices. Perhaps it's just me? I've tried both the Hand Tool and Text Selection Tool with combinations of control/alt/shift/CMD buttons, but none appear to work at the moment.

**Comment by dstillman** [comment]
https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md

Thanks, but please post all bug reports and feature requests to the [Zotero Forums](https://forums.zotero.org).
