### ISSUE TITLE
Feature Request: Improved Text-Editor in PDF Annotation Bubbles

### ISSUE THREAD

**Issue by chrisyeh96** [zotero/pdf-reader#67]
(Copying https://forums.zotero.org/discussion/90502/ here)

I love the new built-in PDF reader. However, I wish you could add 3 more features to the built in note annotation bubbles.

1. Add buttons to underline and strikethrough text in notes annotation bubbles.

    This should be fairly straightforward by adding new entries to the "actions" array:

    https://github.com/zotero/pdf-reader/blob/65bb0ea542694d8a88a6c1aacb8488274ad96c03/src/components/editor.js#L131

    After all, underlining and strikethrough are already supported by `Document.execCommand()`: https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

2. Support for keyboard shortcuts to bold, underline, and italicize text in the notes bubble. Ideally keyboard shortcuts to superscript / subscript text as well.

3. Support for writing LaTeX in note annotation bubbles.

    See https://forums.zotero.org/discussion/comment/385574

**Comment by dstillman** [comment]
Please post all feature requests to the forums.

https://github.com/zotero/zotero/blob/master/CONTRIBUTING.md
