### ISSUE TITLE
I don't kown how to make the pdf reader FULLSCREEN in zotero.

### ISSUE THREAD

**Issue by geek-mr-xie** [zotero/pdf-reader#75]
I need the feature to make the pdf file fullscreen to concentrate, please add this feature to zotero.
I think it is very helpful to use all the screen area to read pdfs, especially in **16:9 devices** . Zotero is very useful to manage my research resources, if the preview function can makes the full use of my screen then zotero is my ONLY software to manage and review articles, so please add the FULLSCREEN button and the sortcut to zotero.

thanks a lot

**Comment by mrtcode** [comment]
Please post feature requests to the [Zotero Forums](https://forums.zotero.org).

**Comment by geek-mr-xie** [comment]
> Please post feature reque

Thanks for your attention！
