### ISSUE TITLE
Is it possible to make the highlight colour more yellowish to a light yellow tone #f3fa00?

### ISSUE THREAD

**Issue by iintrigued** [zotero/pdf-reader#86]
https://github.com/zotero/pdf-reader/blob/9ba10b2e8e942a54e2652cc438a5da04f921556b/src/lib/colors.js#L4

Current yellow colour for highlighting is more orangish than yellow and it makes reading black coloure text more harder. Would it be possible to change it a lighter yellow tone e.g. #f3fa00?

**Comment by dstillman** [comment]
Please post all feature requests and bug reports to the Zotero Forums.
