### ISSUE TITLE
Web library: Don't open sidebar by default if no annotations

### ISSUE THREAD

**Issue by dstillman** [zotero/pdf-reader#92]
https://github.com/zotero/pdf-reader/issues/91#issuecomment-1224914061

**Comment by mrtcode** [comment]
How about external annotations that asynchronously come from pdf-worker (can take time)? I guess if there aren't Zotero annotations, then we don't open sidebar.

**Comment by dstillman** [comment]
Yeah, can we start closed if no Zotero annotations and open the sidebar if we find any external annotations?

Alternatively, do we ever need to open the sidebar by default on the web library? I think we did it on desktop more to highlight the new functionality, but it's not like you can't still see annotations in the PDF.

**Comment by mrtcode** [comment]
> Yeah, can we start closed if no Zotero annotations and open the sidebar if we find any external annotations?

That would be too weird to suddenly open the sidebar after like 1, 2 or 4 seconds once annotation extraction finishes. PDF.js then needs to rerender pages which is not good.

So for now we can just don't show anything.

**Comment by dstillman** [comment]
OK, sounds good.
